#!/usr/bin/env python

import EmelbeeStats
import argparse


parser = argparse.ArgumentParser()

parser.add_argument('year', help='Four digit year')
parser.add_argument('month', help='Two digit Month')
parser.add_argument('day', help='Two digit day')
parser.add_argument('-f', '--filename', help='A local JSON file to get ' +\
                    'scores from, instead of hitting the MLB API')
parser.add_argument('--team', help='Get Info for a Specfic Team' )
parser.add_argument('--debug', help='Run in Debug Mode', action='store_true')

args = parser.parse_args()

stats = EmelbeeStats.EmelbeeStats(args.year, args.month,
                                  args.day, args.filename, args.debug)

print stats.team_scores()
