#!/usr/bin/env python

from flask import Flask, request, redirect
import twilio.twiml
import EmelbeeStats
 
app = Flask(__name__)

stats = EmelbeeStats.EmelbeeStats('2015', '06', '15', 'master_scoreboard.json.sample')
 
@app.route("/scores", methods=['GET'])
def show_team_scores():
    """Respond to incoming calls with a simple text message."""
    
    resp = twilio.twiml.Response()
    resp.message(stats.team_scores()) 
    return str(resp)
 
if __name__ == "__main__":
    app.run(host='0.0.0.0', debug=True)
